#!/bin/bash

# Script to run all my startup stuff with Plasma. It does both background tasks (like Hydroxide, the open-source, command-line only ProtonMail bridge) and desktop apps. The reason it does desktop apps is because I want them on particular workspaces.

# Hydroxide needs to be started before Thunderbird so Thunderbird can connect to it
hydroxide serve &
kstart5 --desktop 3 discord
kstart5 --desktop 3 spotify
kstart5 --desktop 3 thunderbird
sleep 1
kstart5 --desktop 2 firefox
# This doesn't work. I'm hoping to replace it with https://gitlab.com/WhyNotHugo/darkman at some point.
# So uhhhh... I tried to use darkman, and it made plasma fuck itself so hard that it broke my entire machine (as far as I can tell). Safe to say, I'm not fuckin' doing that again.
#python3 ~/scripts/autodarkmode.py &
~/scripts/polybar_run &
